// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: cert_manager.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain       string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Certificates string `protobuf:"bytes,2,opt,name=certificates,proto3" json:"certificates,omitempty"`
}

func (x *ClientAuth) Reset() {
	*x = ClientAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cert_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuth) ProtoMessage() {}

func (x *ClientAuth) ProtoReflect() protoreflect.Message {
	mi := &file_cert_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuth.ProtoReflect.Descriptor instead.
func (*ClientAuth) Descriptor() ([]byte, []int) {
	return file_cert_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ClientAuth) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ClientAuth) GetCertificates() string {
	if x != nil {
		return x.Certificates
	}
	return ""
}

type ServerAuthToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cryptotoken []byte `protobuf:"bytes,1,opt,name=cryptotoken,proto3" json:"cryptotoken,omitempty"`
}

func (x *ServerAuthToken) Reset() {
	*x = ServerAuthToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cert_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerAuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAuthToken) ProtoMessage() {}

func (x *ServerAuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_cert_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAuthToken.ProtoReflect.Descriptor instead.
func (*ServerAuthToken) Descriptor() ([]byte, []int) {
	return file_cert_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ServerAuthToken) GetCryptotoken() []byte {
	if x != nil {
		return x.Cryptotoken
	}
	return nil
}

type ClientAuthTokenACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CryptotokenACK []byte `protobuf:"bytes,1,opt,name=cryptotokenACK,proto3" json:"cryptotokenACK,omitempty"`
}

func (x *ClientAuthTokenACK) Reset() {
	*x = ClientAuthTokenACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cert_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuthTokenACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthTokenACK) ProtoMessage() {}

func (x *ClientAuthTokenACK) ProtoReflect() protoreflect.Message {
	mi := &file_cert_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthTokenACK.ProtoReflect.Descriptor instead.
func (*ClientAuthTokenACK) Descriptor() ([]byte, []int) {
	return file_cert_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ClientAuthTokenACK) GetCryptotokenACK() []byte {
	if x != nil {
		return x.CryptotokenACK
	}
	return nil
}

var File_cert_manager_proto protoreflect.FileDescriptor

var file_cert_manager_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x33, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3c, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x43, 0x4b, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x43, 0x4b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x41, 0x43, 0x4b, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cert_manager_proto_rawDescOnce sync.Once
	file_cert_manager_proto_rawDescData = file_cert_manager_proto_rawDesc
)

func file_cert_manager_proto_rawDescGZIP() []byte {
	file_cert_manager_proto_rawDescOnce.Do(func() {
		file_cert_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_cert_manager_proto_rawDescData)
	})
	return file_cert_manager_proto_rawDescData
}

var file_cert_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cert_manager_proto_goTypes = []interface{}{
	(*ClientAuth)(nil),         // 0: certmanagerproto.ClientAuth
	(*ServerAuthToken)(nil),    // 1: certmanagerproto.ServerAuthToken
	(*ClientAuthTokenACK)(nil), // 2: certmanagerproto.ClientAuthTokenACK
}
var file_cert_manager_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cert_manager_proto_init() }
func file_cert_manager_proto_init() {
	if File_cert_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cert_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cert_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerAuthToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cert_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuthTokenACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cert_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cert_manager_proto_goTypes,
		DependencyIndexes: file_cert_manager_proto_depIdxs,
		MessageInfos:      file_cert_manager_proto_msgTypes,
	}.Build()
	File_cert_manager_proto = out.File
	file_cert_manager_proto_rawDesc = nil
	file_cert_manager_proto_goTypes = nil
	file_cert_manager_proto_depIdxs = nil
}
